version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: homeboard
      POSTGRES_PASSWORD: homeboard
      POSTGRES_DB: homeboard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "homeboard" ]
      interval: 5s
      retries: 10
  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
volumes:
  db_data:

